version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '4001:4001'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apebl-oms-dev
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
